version: "3.8"
name: 'boxit-api'
services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: boxit_mssql
    restart: always
    env_file:
      - .env
    ports:
      - '1433:1433'
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      my-network-api:
  mongodb:
    image: mongo:6
    container_name: boxit_logs
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      my-network-api:
  api:
    build:
      context: .
      target: development
    container_name: boxit_api
    command: npm run dev
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mssql
      - mongodb
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      my-network-api:
volumes:
  mssql_data:
  mongo_data:
networks:
  my-network-api:
    driver: bridge

